### ISSUE TITLE
Why are mean/variance all 127.5 for tiny-imagenet-200?

### ISSUE THREAD

**Issue by averyma** [snu-mllab/Co-Mixup#5]
https://github.com/snu-mllab/Co-Mixup/blob/2a7681601ee972892435ae080494a4f0907e595a/load_data.py#L48

**Comment by Janghyun1230** [comment]
Hello! 
To be clear, it's 0.5 (=127.5/255) for each channel. I borrowed the setting from manifold mixup codes ([link](https://github.com/vikasverma1077/manifold_mixup/blob/master/supervised/load_data.py)).

**Comment by averyma** [comment]
Thank you very much for the fast reply!

You are right, but the mean/std for that dataset is definitely not 0.5 though. 

I suppose the results reported in the paper are all using 0.5's?

Also, did you try using the correct mean/std for normalization? Like the same way we compute the mean/std for cifar10/cifar100.

Thanks!

**Comment by Janghyun1230** [comment]
Yes, all the reported values including baselines are using 0.5. I didn't try experiments with the correct normalization.

**Comment by averyma** [comment]
Thank you for the response! I will close the issue.
