### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by Abdulaziz-KTA** [snu-mllab/Co-Mixup#7]
error while tring download tiny imagenet

![image](https://user-images.githubusercontent.com/46826627/172592331-2a306769-e925-44c3-97c6-3dcaf2acf872.png)

**Comment by Janghyun1230** [comment]
Hello, if there are no available sources, then I will share my dataset.
Please let me know if you can't obtain the dataset until now.

**Comment by Abdulaziz-KTA** [comment]
@Janghyun1230  thank you I found the dataset

**Comment by Abdulaziz-KTA** [comment]
thx
