### ISSUE TITLE
Question about imagenet vanilla performance

### ISSUE THREAD

**Issue by Neonsign247** [snu-mllab/Co-Mixup#8]
Hello. Thank you for your great work.

Currently, I'm trying to reproduce vanilla performance with your imagenet_fast protocol. However, my model 2-3% behind with your configuration. Can you share tricks (data augmentation or optimized configuration) or training log?

**Comment by Janghyun1230** [comment]
duplicated issue: https://github.com/snu-mllab/PuzzleMix/issues/10
